export const ROUTES = {
  HOME: '/',
  CONVERSATION: '/conversation/:id',
  SESSIONS: '/sessions',
  SESSION_DETAIL: '/sessions/:id',
  SETTINGS: '/settings',
  SETTINGS_GENERAL: '/settings/general',
  SETTINGS_MEMORY_SETTINGS: '/settings/memory-settings',
  SETTINGS_SESSIONS: '/settings/sessions',
  SETTINGS_MODEL: '/settings/model',
  SETTINGS_SKILLS: '/settings/skills',
  SETTINGS_PLUGINS: '/settings/plugins',
  SETTINGS_MCP: '/settings/mcp',
  SETTINGS_MEMORY: '/settings/memory',
  SETTINGS_GATEWAY: '/settings/gateway',
  SETTINGS_CRON: '/settings/cron',
  SETTINGS_ARCHIVED_CHATS: '/settings/archived-chats',
  MODEL: '/model',
  SKILLS: '/skills',
  PLUGINS: '/plugins',
  MCP: '/mcp',
  MEMORY: '/memory',
  GATEWAY: '/gateway',
  CRON: '/cron',
} as const;

export type RoutePath = (typeof ROUTES)[keyof typeof ROUTES];
